- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnDeleteFrom.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnDeleteWhereName.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/DefaultSelectQueryBuilder.java
- diana-column/src/test/java/org/jnosql/diana/api/column/query/DefaultDeleteQueryBuilderTest.java
- diana-column/src/test/java/org/jnosql/diana/api/column/query/DefaultSelectQueryBuilderTest.java
- diana-core/src/main/java/org/jnosql/diana/api/Settings.java
- diana-core/src/main/java/org/jnosql/diana/api/reader/EnumValueReader.java
- diana-document/src/main/java/org/jnosql/diana/api/document/DefaultDocumentCondition.java
- diana-document/src/main/java/org/jnosql/diana/api/document/Document.java
- diana-document/src/main/java/org/jnosql/diana/api/document/DocumentEntity.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultDeleteQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultDocumentDeleteQuery.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultDocumentQuery.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultSelectQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteFrom.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteNameCondition.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteNotCondition.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteWhere.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteWhereName.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentFrom.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentNameCondition.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentNotCondition.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentWhere.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentWhereName.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/ReadOnlyDocumentCondition.java
- diana-document/src/test/java/org/jnosql/diana/api/document/query/DefaultDeleteQueryBuilderTest.java
- diana-document/src/test/java/org/jnosql/diana/api/document/query/DefaultSelectQueryBuilderTest.java
- diana-key-value/src/main/java/org/jnosql/diana/api/key/KeyValueEntity.java
Ref: https://github.com/eclipse/jnosql-diana/issues/104
```java
DocumentQuery query = select().from(columnFamily).where("name").eq(name).or("age").gt(10).build();
DocumentQuery query = select().from(columnFamily).where("name").eq(name).and("age").gt(10).build();
DocumentQuery query = select().from(columnFamily).where("name").not().eq(name).build();
DocumentQuery query = select().from(columnFamily).where("salary").between(valueA, valueB).build();
```
```java
DocumentDeleteQuery query = delete().from(columnFamily).where("name").eq(name).build();
DocumentDeleteQuery query = delete().from(columnFamily).where("name").not().eq(name).build();
DocumentDeleteQuery query = delete().from(columnFamily).where("name").eq(name).and("age").gt(10).build();
DocumentDeleteQuery query = …
```
> Improves the fluent API in Column and Document in the condition

- diana/diana-core/src/main/java/org/jnosql/diana/reader/MapTypeReferenceReader.java
- diana/diana-core/src/main/java/org/jnosql/diana/reader/NavigableSetTypeReferenceReader.java
- diana/diana-core/src/main/java/org/jnosql/diana/reader/OptionalTypeReferenceReader.java
- diana/diana-core/src/main/java/org/jnosql/diana/reader/SetTypeReferenceReader.java
- diana/diana-core/src/main/java/org/jnosql/diana/reader/StreamTypeReferenceReader.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/ListTypeReferenceReaderTest.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/MapTypeReferenceReaderTest.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/NavigableSetTypeReferenceReaderTest.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/OptionalTypeReferenceReaderTest.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/QueueTypeReferenceReaderTest.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/SetTypeReferenceReaderTest.java
- diana/diana-core/src/test/java/org/jnosql/diana/reader/StreamTypeReferenceReaderTest.java
Eclipse-the-IDE considers these double semicolons syntax errors.
> Removes double semicolons on import statements

- communication/communication-core/src/main/java/org/eclipse/jnosql/communication/ParamValue.java
I found the earlier message for the null check in `ParamValue` to be confusing in practice, so this change is just to clarify that the query parameter value cannot be null.
> Clarify exception message in ParamValue#validValue

- communication/communication-core/src/main/java/org/eclipse/jnosql/communication/writer/ValueWriterDecorator.java
The only change here is to switch a direct use of `java.util.ServiceLoader` in `ValueWriterDecorator` to use `ServiceLoaderProvider` instead.
> Switch ValueWriterDecorator to use ServiceLoaderProvider

- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/WhereTest.java
Fixed test assertions to use `assertFalse` assertion method because `assertEquals` assertion method doesn't call the target object `equals` method when the 1st provided parameter is `null`:
FYI, here are some snippet codes from the Junit Jupiter Assertions API that I'm talking about:
The `org.junit.jupiter.api.AssertEquals.assertEquals()` method:
```java
static void assertEquals(Object expected, Object actual, Supplier<String> messageSupplier) {
if (!objectsAreEqual(expected, actual)) {
failNotEqual(expected, actual, messageSupplier);
}
}
```
And the `org.junit.jupiter.api.AssertionUtils.objectsAreEqual() `:
```java
static boolean objectsAreEqual(Object obj1, Object obj2) {
if (obj1 == null) {
return (obj2 == null);
}
return obj1.equals(obj2);
}
```
@otaviojava, could you review this PR, …
> Fixed test assertions in order to improve the test coverage

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassScanner.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/UnsupportedRepositoryFilter.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/UnsupportedRepositoryFilterTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/test/entities/User.java
Ignores any data repository where the entity has an annotation that Eclipse JNoSQL does not support.
- Create a filter to ignore unsupported annotations on repositories interfaces.
> Fix validation scan

- CONTRIBUTING.adoc
Closes #361 
Clear commit instructions based on the given specifications have been added to the contributing.adoc file.
New section includes the following: 
1. Types of Commits
2. Examples of commits
3. Formatting Commit messages
I have signed the ECA( Eclipse Contributor Agreement 3.1.0) and am aware of the terms by which the contribution has been provided to the project.  
Signed-off-by: Viraj Shah <veer15102003@gmail.com>
> Added commit section to contributing.adoc

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/AbstractColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/query/RepositoryType.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/query/RepositoryTypeTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/AbstractDocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentCrudRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractGraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/AbstractKeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxyTest.java
Add support for default methods on an interface and also extra interface:
```java
interface BaseQuery<T> {
List<T> findByScoreLessThan(int score);
default List<T> lessTen() {
return this.findByScoreLessThan(10);
}
}
@Repository    
interface PersonRepository extends PageableRepository<Person, Long>, BaseQuery<Person> {
List<Person> findByName(String name);
List<Person> findByNameNot(String name);
default Map<Boolean, List<Person>> partcionate(String name) {
Objects.requireNonNull(name, "name is required");
Map<Boolean, List<Person>> map = new HashMap<>();
map.put(true,  findByName(name));
map.put(false, findByNameNot(name));
return map;
}
}
@Repository    
interface Garage extends PageableRepository<Car, Long>, BaseQuery<Car> {
}
```
So, the project will support both:
```java
@Inject …
```
> Add support for default method on repositories

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ParameterMetaDataBuilder.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassScannerTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ConstructorMetadataBuilderTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ParameterMetaDataBuilderTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/test/entities/constructor/Smartphone.java
- Enhance the field name auto-detection when given constructor parameters of Record classes are annotated with `@Column` defined with an empty name.
It will improve the dev experience, allowing developers to use Records with fields annotated with `@Column` without the necessity to provide a given column name;
> Field name auto-detection when given a constructor parameters of Record classes are annotated with @Column defined with empty name.

- CONTRIBUTING.adoc
My change suggestion is about `docs`:
1. The jnosql-extension repo URL is wrong.
Thank you.
> docs: fixing jnosql extensions url

- jnosql-communication/jnosql-communication-document/src/main/java/org/eclipse/jnosql/communication/document/SelectQueryParser.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/MapperSelectTest.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnCrudRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/MapperSelectTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentCrudRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxyTest.java
1. `Mockito.eq` is not needed in that's cases.
2. `public` keyword is not needed.
3. `sort.isAscending() == true` is not needed.
Thank you.
> refact: unecessary matcher

- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/DefaultQueryConditionTest.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/WhereTest.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/method/MethodConditionTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphCrudRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
1. In `assertEquals` the _first_ args must be the expected.
2. `public` keyword is not needed.
3. Some cases are two/three white lines in a row, I mean it's too much, so I removed them.
Thank you.
> (refact): swap expected vs actual

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/DefaultColumnTemplate.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/DefaultDocumentTemplate.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/DefaultGraphTemplate.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/DefaultGraphTraversalSourceTemplate.java
Ref: https://github.com/eclipse/jnosql/issues/400
- Added no-args constructor into the injectable beans;
> Fix - Added no-args constructor into the injectable beans

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultEntitiesMetadata.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/EntitiesMetadata.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultEntitiesMetadataTest.java
- Update the EntitiesMetadata, making lazy loading when the entity is not loaded from the extension
Fixes this issue: https://github.com/quarkiverse/quarkus-jnosql/issues/25
> Update Entities Medatada for lazy loading

- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
1. Removing the `AssertNotNull` with hashCode(), because hashCode() is primitive.
2. It was missing a **H** in shoudReturnHas**h**Code:
1. I had the idea _to suggest_ `shouldReturnSameHashCode`
3. `personRepository.equals(personRepository)`, returns false, i had the idea _to suggest_:
1. Rename de method to: `shouldReturnNotNull`
2. Use only one argument
4. Removed an import that was lost.
Thank you.
> refact: assertNotNull with primitive

- .gitignore
- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ParameterMetaDataBuilder.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassScannerTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ReflectionsTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/test/entities/constructor/Tablet.java
- Fixes ParameterMedataData to not throw NullPointException when it's built with a Parameter without `@Column` or `@Id` annotations;
- Tests enhancement for Java Records integration;
> Fixes ParameterMedataData to not thrown NullPointException when it's built with a Parameter without @Column or @Id annotations

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/Reflections.java
Fixes: https://github.com/eclipse/jnosql/issues/407
- Fixes Reflections.getConstructor() method logic to detect constructors with parameters annotated with @Id or @Column
> Fixes issue #407: Fixes Reflections.getConstructor() method logic to detect constructors with parameters annotated with @Id or @Column

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScanner.java
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilter.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilterTest.java
Solves:
https://github.com/eclipse/jnosql/issues/436
> Fixes the Lack of descriptive error when trying to inject a Repository with type without @Entity annotation

- jnosql-communication/jnosql-communication-column/src/test/java/org/eclipse/jnosql/communication/column/ColumnDeleteQueryParamsTest.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/ParamsTest.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/DefaultQueryValueTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultConstructorBuilderTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultEntityMetadataTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultFieldMetadataTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultGenericFieldMetaDataTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/EmbeddedFieldMetadataTest.java
1. AssertJ has specific methods for _hashcode_ and _tostring_, maybe, should be good, use them.
Thank you.
> refact: using especific methods in assertj

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/AbstractColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/ColumnParameterBasedQuery.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnParameterBasedQueryTest.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/query/AbstractRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/query/AnnotationOperation.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/query/RepositoryType.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/repository/RepositoryReflectionUtils.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/core/query/AbstractRepositoryTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/core/query/AnnotationOperationTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/core/query/RepositoryTypeTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/core/repository/RepositoryReflectionUtilsTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/AbstractDocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/DocumentParameterBasedQuery.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentParameterBasedQueryTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractGraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractQueryConvert.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/CountQueryConverter.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/DeleteQueryConverter.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/GraphQueryMethod.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/SelectQueryConverter.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/AbstractKeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/query/DefaultKeyValueRepositoryTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxyTest.java
- Add support to long
- Add support to math parameter
> Update Query supporting param match

- MAPPING.adoc
Changes:
- Fix typo in MAPPING.adoc documentation file.
> docs: fix typo in MAPPING.adoc

- .github/workflows/java-17.yml
- .github/workflows/java-21.yml
Bump up the actions that use Node.js 20 runtime:
- actions/checkout@v3 to v4;
- actions/cache@v3 to v4;
- actions/setup-java@v3 to v4;
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> ci: update deprecated actions

- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandler.java
- Fixed recursive call issue on CustomRepositoryHandler;
Here is the completed maven log: [mvn.log](https://github.com/user-attachments/files/15538678/mvn.log)
A piece of the maven log that shows the mentioned issue:
``` console
[INFO] Running org.eclipse.jnosql.databases.mongodb.integration.CustomRepositoryIntegrationTest
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 4.824 s <<< FAILURE! -- in org.eclipse.jnosql.databases.mongodb.integration.CustomRepositoryIntegrationTest
[ERROR] org.eclipse.jnosql.databases.mongodb.integration.CustomRepositoryIntegrationTest.shouldDelete -- Time elapsed: 0.925 s <<< ERROR!
java.lang.StackOverflowError
at java.base/java.lang.StackStreamFactory$AbstractStackWalker.callStackWalk(Native Method)
at …
```
> fix: resolved recursive call issue

- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/DefaultValue.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/DefaultValueTest.java
The error message should contain the type and not a supplier object.
It took me some time to figure out what was wrong with my code with a message like:
>The type org.eclipse.jnosql.mapping.reflection.ReflectionClassConverter$$Lambda$1081/0x00000208cea01230@24584a22 is not supported
Cheers,
D.
> minor error message fix

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScannerTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultArrayParameterMetaDataTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultArrayParameterMetaDataWhenEntityClassIsRecordTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultArrayParameterMetaDataWhenEntityIsRegularClassTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/entities/constructor/Game.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/entities/constructor/Player.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/ParameterConverter.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/EntityConverterConstructorTest.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/EntityConverterTest.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/entities/constructor/BookBag.java
Ref. #544 
-  Adding support to embedded array columns onto entities that are implemented using the Java Record feature;
> [FIX] Adding support to embedded array columns onto entities that are implemented using the Java Record feature

- CHANGELOG.adoc
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/DatabaseManager.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/AbstractSemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/SemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/DefaultSemiStructuredTemplateTest.java
Fixes: https://github.com/eclipse/jnosql/issues/550
> Fixes: [BUG] Using skip with DocumentTemplate does not have any effect #550

- CHANGELOG.adoc
- README.adoc
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/Configurations.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/DatabaseManager.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/AbstractSemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/SemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/DefaultSemiStructuredTemplateTest.java
- Define default behavior of cursor as single field pagination
> Disable cursor plus elements

- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilter.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScannerTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilterTest.java
Upon doing a retrospective on #559 it was pointed out to me that if Jakarta Config is accepted into Jakarta EE 12 then using the `@Repository` provider attribute of `Eclipse JNoSQL` might be problematic if that attribute is configurable using Jakarta Config.  If Jakarta Config follows the Microprofile Spec the space should not be an issue, but we could avoid potential issues by transitioning to `Eclipse_JNoSQL` or something without a space.
I'm also open to suggestions.
> refactor: update provider name to be more compatible with Jakarta Config

- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/ValueUtil.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/UUIDValueReader.java
- jnosql-communication/jnosql-communication-core/src/main/resources/META-INF/services/org.eclipse.jnosql.communication.ValueReader
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/ValueUtilTest.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/reader/UUIDValueReaderTest.java
- pom.xml
- Include ValueUtil
- Create UUIDValueReader
> Enhance ValueUtil

- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultConstructorBuilder.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScannerTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultConstructorBuilderTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/entities/constructor/Counter.java
This change avoids an IllegalArgumentException when working with classes with primitive arguments when the underlying values are not in the data source. It modifies DefaultConstructorBuilder#addEmptyParameter method to check the type and use default values for primitives, falling back to `null` for objects.
> fix: handle empty primitive parameters in DefaultConstructorBuilder

- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultCollectionFieldMetadata.java
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultMapFieldMetadata.java
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/Reflections.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/ReflectionClassConverterTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/entities/JsonContainer.java
I found that a `@Column` property where the type is a non-generic subclass/subinterface of a Collection or Map type (like `JsonObject`) caused a ClassCastException. This change will try to find the actual declaration of the Map or Collection type to find its type arguments.
I expect that this still wouldn't handle the further-down case of a templated type that then uses that generic type in a property, but that would be a bigger problem to solve.
> fix: improve handling of collection subclass columns

- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/repository/DynamicReturnConverter.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/spi/DocumentExtension.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandler.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/SemiStructuredRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandlerTest.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/query/People.java
This allows extending some classes in the driver for Jakarta Persistence.
Adds support for JDQL queries that refer to parameters by names, e.g. :name, not only by index, e.g. ?1.
Support boolean return type, which is required to pass the Data 1.0 TCK for Jakarta Persistence entities, not for NoSQL entities. The test is challenged: https://github.com/jakartaee/data/issues/923
> feat: Open some classes for inheritance, support named method parameters

- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/ParamValue.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/Conditions.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/DefaultSelectQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/AbstractSemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/MapperSelect.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/MappingQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepository.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/BaseSemiStructuredRepository.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandler.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/DynamicQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/SemiStructuredParameterBasedQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/SemiStructuredRepositoryProxy.java
This enhances the JDQL query parser to pass the information about non-entity fields to the SelectQuery parsed query.
Also opens several private classes or methods for extending them in drivers or extensions.
> Copy columns to mapped query to pass the information to the repositories (1.1.x)

- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/ParamValue.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/Conditions.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/DefaultSelectQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/AbstractSemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/MapperSelect.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/MappingQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepository.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/BaseSemiStructuredRepository.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandler.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/DynamicQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/SemiStructuredParameterBasedQuery.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/SemiStructuredRepositoryProxy.java
Port of https://github.com/eclipse-jnosql/jnosql/pull/618 to main
This enhances the JDQL query parser to pass the information about non-entity fields to the SelectQuery parsed query.
Also opens several private classes or methods for extending them in drivers or extensions.
> Copy columns to mapped query to pass the information to the repositories

- CHANGELOG.adoc
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/Condition.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/method/AbstractMethodQueryParser.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/method/DeleteByMethodQueryProviderTest.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/method/SelectMethodQueryProviderTest.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/Conditions.java
- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/CriteriaCondition.java
Support for Contains, EndsWith, StartsWith, IgnoreCase.
Includes:
* backport of https://github.com/eclipse-jnosql/jnosql/pull/620 to 1.1.x (brings Contains, EndsWith, StartsWith) - with [this commit](https://github.com/eclipse-jnosql/jnosql/commit/bf4d5c7c684a8294fd6d24c4f6e4bb02d36d9eee)
* support for IgnoreCase
* merge of several checking methods in tests into a single checkConditions, which supports checking nested conditions
> Include support on four new terms on method by query (1.1.x)

- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/method/MethodSelectQuery.java
Not only entity and where as before.
This allows using `MethodSelectQuery` as a key, e.g. for caching
> feat: Equals and hashCode in MethodSelectQuery now consider all fields
