- diana-api/src/main/java/org/apache/diana/api/DefaultValue.java
- diana-api/src/main/java/org/apache/diana/api/document/DefaultDocument.java
- diana-api/src/main/java/org/apache/diana/api/document/DefaultDocumentCollectionEntity.java
- diana-api/src/main/java/org/apache/diana/api/document/Document.java
- diana-api/src/main/java/org/apache/diana/api/document/DocumentCollectionEntity.java
- diana-api/src/main/java/org/apache/diana/api/document/Documents.java
- mongodb-driver/mongodb-document/.gitignore
- mongodb-driver/mongodb-document/mongodb-document-api/.gitignore
- mongodb-driver/mongodb-document/mongodb-document-api/pom.xml
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/apache/diana/mongodb/document/DocumentQueryConversor.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/apache/diana/mongodb/document/MongoDBDocumentCollectionManager.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/apache/diana/mongodb/document/MongoDBDocumentCollectionManagerFactory.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/apache/diana/mongodb/document/MongoDBDocumentConfiguration.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/test/java/org/apache/diana/mongodb/document/DocumentConfigurationUtils.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/test/java/org/apache/diana/mongodb/document/MongoDBDocumentCollectionManagerFactoryTest.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/test/java/org/apache/diana/mongodb/document/MongoDBDocumentCollectionManagerTest.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/test/java/org/apache/diana/mongodb/document/MongoDBDocumentConfigurationTest.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/test/resources/diana-mongodb.properties
- mongodb-driver/mongodb-document/pom.xml
- mongodb-driver/pom.xml
Ref: https://github.com/JNOSQL/diana/issues/23
> Create MongoDB driver

- diana-api/src/main/java/org/apache/diana/api/reader/CalendarReader.java
- diana-api/src/test/java/org/apache/diana/api/reader/CalendarReaderTest.java
add reader for Calendar. 
Add test unit for testing CalendarReader
> CalendarReader #10

- diana-api/src/main/java/org/apache/diana/api/reader/CalendarReader.java
- diana-api/src/main/java/org/apache/diana/api/reader/YearReader.java
- diana-api/src/main/resources/META-INF/services/org.apache.diana.api.ReaderField
- diana-api/src/test/java/org/apache/diana/api/reader/CalendarReaderTest.java
- diana-api/src/test/java/org/apache/diana/api/reader/YearReaderTest.java
Changing the Calendar Reader class to add suggested adjustments and create YearReader with the unit test.
Correct the class YearReader.java and add the class in file org.apache.diana.api.ReaderField
>  Reader field calendar#10 and Reader field Year #15

- cassandra-driver/build.sh
- mongodb-driver/build.sh
- redis-driver/build.sh
> DIANA-36 Create builds scripts with docker to test drivers

- diana-api/src/main/java/org/jnosql/diana/api/reader/LocalDateReader.java
- diana-api/src/test/java/org/jnosql/diana/api/reader/LocalDateReaderTest.java
> DIANA-12 Create ReaderField implementations for java.time.LocalDate

- diana-api/src/main/java/org/jnosql/diana/api/reader/LocalDateReader.java
- diana-api/src/test/java/org/jnosql/diana/api/reader/LocalDateReaderTest.java
DIANA-45 Update LocalDateRender to support parse from Calendar.
fixes #44 
fixes #45
> DIANA-44 Update String parse on LocalDateRender

- hbase-driver/build.sh
> DIANA-42 Fix build.sh for hbase-driver

- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnFamilyManager.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentCollectionManager.java
- diana-api/src/main/java/org/jnosql/diana/api/key/BucketManager.java
https://github.com/JNOSQL/diana/issues/53
> Adds methods to save and update using time to live #53

- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnFamilyManager.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentCollectionManager.java
- diana-api/src/main/java/org/jnosql/diana/api/key/BucketManager.java
Ref: https://github.com/JNOSQL/diana/issues/55
> Adds new methods to support Diana Query language in EntityManager

- diana-api/src/main/java/org/jnosql/diana/api/reader/YearMonthReader.java
- diana-api/src/main/resources/META-INF/services/org.jnosql.diana.api.ReaderField
- diana-api/src/test/java/org/jnosql/diana/api/reader/YearMonthTest.java
Adicionado:
- YearMonthReader.
- YearMonthTest.
- classe no org.jnosql.diana.api.ReaderField.
Referencia
#16
> YearMonthReader #16

- diana-api/src/main/java/org/jnosql/diana/api/reader/YearMonthReader.java
- diana-api/src/main/java/org/jnosql/diana/api/reader/YearReader.java
- diana-api/src/main/java/org/jnosql/diana/api/reader/ZonedDateTimeReader.java
- diana-api/src/main/resources/META-INF/services/org.jnosql.diana.api.ReaderField
- diana-api/src/test/java/org/jnosql/diana/api/reader/ZonedDateTimeReaderTest.java
> DIANA-17 Zoned date time reader

- diana-api/src/main/java/org/jnosql/diana/api/reader/LocalTimeReader.java
- diana-api/src/main/resources/META-INF/services/org.jnosql.diana.api.ReaderField
- diana-api/src/test/java/org/jnosql/diana/api/reader/LocalTimeReaderTest.java
> DIANA-14 - adding LocalTimeReader

- cassandra-driver/cassandra-document/cassandra-column-api/pom.xml
- cassandra-driver/cassandra-document/cassandra-column-tck/pom.xml
- cassandra-driver/cassandra-document/pom.xml
- cassandra-driver/pom.xml
- diana-api/pom.xml
- diana-tck/pom.xml
- hazelcast-driver/halzelcast-key-value/hazelcast-key-value-api/pom.xml
- hazelcast-driver/halzelcast-key-value/pom.xml
- hazelcast-driver/pom.xml
- hbase-driver/hbase-document/hbase-column-api/pom.xml
- hbase-driver/hbase-document/pom.xml
- hbase-driver/pom.xml
- mongodb-driver/mongodb-document/mongodb-document-api/pom.xml
- mongodb-driver/mongodb-document/pom.xml
- mongodb-driver/pom.xml
- pom.xml
- redis-driver/pom.xml
- redis-driver/redis-key-value/pom.xml
- redis-driver/redis-key-value/redis-key-value-api/pom.xml
- redis-driver/redis-key-value/redis-key-value-tck/pom.xml
Changes enconing in project to UTF-8
> Changes enconing in project to UTF-8

- cassandra-driver/cassandra-document/cassandra-column-api/src/main/java/org/jnosql/diana/cassandra/column/CassandraConfiguration.java
- cassandra-driver/cassandra-document/cassandra-column-api/src/main/java/org/jnosql/diana/cassandra/column/CassandraDocumentEntityManager.java
- cassandra-driver/cassandra-document/cassandra-column-api/src/main/java/org/jnosql/diana/cassandra/column/CassandraDocumentEntityManagerFactory.java
- cassandra-driver/cassandra-document/cassandra-column-api/src/test/java/org/apache/diana/cassandra/column/CassandraDocumentEntityManagerTest.java
- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnConfiguration.java
- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnFamilyManagerFactory.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentCollectionManagerFactory.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentConfiguration.java
- diana-api/src/main/java/org/jnosql/diana/api/key/BucketManagerFactory.java
- diana-api/src/main/java/org/jnosql/diana/api/key/KeyValueConfiguration.java
- hazelcast-driver/halzelcast-key-value/hazelcast-key-value-api/src/main/java/org/jnosql/diana/hazelcast/key/HazelCastKeyValueConfiguration.java
- hazelcast-driver/halzelcast-key-value/hazelcast-key-value-api/src/main/java/org/jnosql/diana/hazelcast/key/HazelCastKeyValueEntityManager.java
- hazelcast-driver/halzelcast-key-value/hazelcast-key-value-api/src/main/java/org/jnosql/diana/hazelcast/key/HazelCastKeyValueEntityManagerFactory.java
- hbase-driver/hbase-document/hbase-column-api/src/main/java/org/jnosql/diana/hbase/column/HBaseColumnConfiguration.java
- hbase-driver/hbase-document/hbase-column-api/src/main/java/org/jnosql/diana/hbase/column/HBaseColumnFamilyManager.java
- hbase-driver/hbase-document/hbase-column-api/src/main/java/org/jnosql/diana/hbase/column/HBaseColumnFamilyManagerFactory.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/jnosql/diana/mongodb/document/MongoDBDocumentCollectionManager.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/jnosql/diana/mongodb/document/MongoDBDocumentCollectionManagerFactory.java
- mongodb-driver/mongodb-document/mongodb-document-api/src/main/java/org/jnosql/diana/mongodb/document/MongoDBDocumentConfiguration.java
- redis-driver/redis-key-value/redis-key-value-api/src/main/java/org/jnosql/diana/redis/key/RedisConfiguration.java
- redis-driver/redis-key-value/redis-key-value-api/src/main/java/org/jnosql/diana/redis/key/RedisKeyValueEntityManager.java
- redis-driver/redis-key-value/redis-key-value-api/src/main/java/org/jnosql/diana/redis/key/RedisKeyValueEntityManagerFactory.java
Updates API follows suggestion
> Updates API follows suggestion

- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnFamilyManager.java
- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnFamilyManagerAsync.java
- diana-api/src/main/java/org/jnosql/diana/api/column/ColumnFamilyManagerFactory.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentCollectionManager.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentCollectionManagerAsync.java
- diana-api/src/main/java/org/jnosql/diana/api/document/DocumentCollectionManagerFactory.java
Just to start the discussion:
https://github.com/JNOSQL/diana/issues/75
> Does make sense have sync and async behavior on different interfaces?

- src/main/java/org/jnosql/diana/api/NonUniqueResultException.java
- src/main/java/org/jnosql/diana/api/column/ColumnCondition.java
- src/main/java/org/jnosql/diana/api/column/ColumnDeleteQuery.java
- src/main/java/org/jnosql/diana/api/column/ColumnFamilyManager.java
- src/main/java/org/jnosql/diana/api/column/ColumnFamilyManagerAsync.java
- src/main/java/org/jnosql/diana/api/column/ColumnQuery.java
- src/main/java/org/jnosql/diana/api/column/DefaultColumnCondition.java
- src/main/java/org/jnosql/diana/api/column/DefaultColumnDeleteQuery.java
- src/main/java/org/jnosql/diana/api/document/DefaultDocumentCondition.java
- src/main/java/org/jnosql/diana/api/document/DefaultDocumentDeleteQuery.java
- src/main/java/org/jnosql/diana/api/document/DocumentCollectionManager.java
- src/main/java/org/jnosql/diana/api/document/DocumentCollectionManagerAsync.java
- src/main/java/org/jnosql/diana/api/document/DocumentCondition.java
- src/main/java/org/jnosql/diana/api/document/DocumentDeleteQuery.java
- src/main/java/org/jnosql/diana/api/document/DocumentQuery.java
- src/main/java/org/jnosql/diana/api/key/BucketManager.java
- src/test/java/org/jnosql/diana/api/column/DefaultColumnDeleteQueryTest.java
- src/test/java/org/jnosql/diana/api/column/DefaultColumnQueryTest.java
- src/test/java/org/jnosql/diana/api/document/DefaultDocumentConditionTest.java
- src/test/java/org/jnosql/diana/api/document/DefaultDocumentDeleteQueryTest.java
- src/test/java/org/jnosql/diana/api/document/DefaultDocumentQueryTest.java
Ref: https://github.com/JNOSQL/artemis/issues/20
> Repository.save discussion

- diana-column/src/main/java/org/jnosql/diana/api/column/ColumnConfiguration.java
- diana-column/src/main/java/org/jnosql/diana/api/column/ColumnConfigurationAsync.java
- diana-document/src/main/java/org/jnosql/diana/api/document/DocumentConfiguration.java
- diana-document/src/main/java/org/jnosql/diana/api/document/DocumentConfigurationAsync.java
- diana-key-value/src/main/java/org/jnosql/diana/api/key/KeyValueConfiguration.java
Signed-off-by: Mateus Malaquias <mateusmalaquiasdev@outlook.com>
> Fixing javadoc use @see with link

- pom.xml
Signed-off-by: Lucas Furlaneto <lucasfurlaneto.s@gmail.com>
> changed maven sonar plugin

- diana-column/src/main/java/org/jnosql/diana/api/column/query/BaseQueryBuilder.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnDeleteNameCondition.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnNameCondition.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/DefaultDeleteQueryBuilder.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/DefaultSelectQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/BaseQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultDeleteQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultSelectQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteNameCondition.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentNameCondition.java
https://github.com/eclipse/jnosql-artemis/issues/54
> Improve with query date

- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnBuild.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnDeleteFrom.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnDeleteQueryBuild.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnDeleteWhere.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnFrom.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnLimit.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnNameOrder.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnQueryBuild.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnSkip.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/ColumnWhere.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/DefaultDeleteQueryBuilder.java
- diana-column/src/main/java/org/jnosql/diana/api/column/query/DefaultSelectQueryBuilder.java
- diana-column/src/test/java/org/jnosql/diana/api/column/query/DefaultDeleteQueryBuilderTest.java
- diana-column/src/test/java/org/jnosql/diana/api/column/query/DefaultSelectQueryBuilderTest.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultDeleteQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DefaultSelectQueryBuilder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteQueryBuild.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentDeleteWhere.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentFrom.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentLimit.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentNameOrder.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentQueryBuild.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentSkip.java
- diana-document/src/main/java/org/jnosql/diana/api/document/query/DocumentWhere.java
- diana-document/src/test/java/org/jnosql/diana/api/document/query/DefaultDeleteQueryBuilderTest.java
- diana-document/src/test/java/org/jnosql/diana/api/document/query/DefaultSelectQueryBuilderTest.java
```java
DocumentCollectionManager manager = null;
//delete
delete().from(collection).execute(manager);
//select
List<DocumentEntity> entities = select().from(collection).execute(manager);
```
> Improve Query

- README.adoc
Signed-off-by: Antonio Zaitoun <tony.z.1711@gmail.com>
> Removed line duplication in README

- mapping/artemis-graph/src/test/java/org/jnosql/artemis/graph/DefaultVertexTraversalTest.java
Signed-off-by: Emerson Mendes <emerson.emendes@gmail.com>
> typo fixes

- README.adoc
> #Added circle CI link to docs

- README.adoc
Signed-off-by: Fernando Almeida <almeidascvn@gmail.com>
> Fix CI Server naming

- artemis/artemis-column/src/test/java/org/eclipse/jnosql/artemis/column/query/ColumnRepositoryProxyTest.java
- artemis/artemis-document/src/test/java/org/eclipse/jnosql/artemis/document/query/DocumentRepositoryProxyTest.java
- diana/diana-query/src/main/java/org/eclipse/jnosql/diana/query/method/AbstractMethodQueryProvider.java
- diana/diana-query/src/main/java/org/eclipse/jnosql/diana/query/method/FindByMethodQueryProvider.java
- diana/diana-query/src/test/java/org/eclipse/jnosql/diana/query/method/DeleteByMethodQueryProviderTest.java
- diana/diana-query/src/test/java/org/eclipse/jnosql/diana/query/method/FindByMethodQueryProviderTest.java
- diana/diana-query/src/test/java/org/eclipse/jnosql/diana/query/method/MethodQueryTest.java
Ref: https://github.com/eclipse/jnosql/issues/234
> Enables a query by subentity in the Repository query

- artemis/artemis-column/src/main/java/org/eclipse/jnosql/artemis/column/ColumnFieldConverter.java
- artemis/artemis-column/src/main/java/org/eclipse/jnosql/artemis/column/ColumnFieldConverters.java
- artemis/artemis-column/src/main/java/org/eclipse/jnosql/artemis/column/ColumnFieldValue.java
- artemis/artemis-column/src/main/java/org/eclipse/jnosql/artemis/column/DefaultColumnFieldValue.java
- artemis/artemis-core/src/main/java/org/eclipse/jnosql/artemis/DefaultConverters.java
- artemis/artemis-core/src/main/java/org/eclipse/jnosql/artemis/reflection/AbstractFieldMapping.java
- artemis/artemis-core/src/main/java/org/eclipse/jnosql/artemis/reflection/DefaultFieldMapping.java
- artemis/artemis-core/src/main/java/org/eclipse/jnosql/artemis/reflection/FieldMapping.java
- artemis/artemis-core/src/main/java/org/eclipse/jnosql/artemis/reflection/FieldMappingBuilder.java
- artemis/artemis-core/src/main/java/org/eclipse/jnosql/artemis/reflection/GenericFieldMapping.java
- artemis/artemis-document/src/main/java/org/eclipse/jnosql/artemis/document/DefaultDocumentFieldValue.java
- artemis/artemis-document/src/main/java/org/eclipse/jnosql/artemis/document/DocumentFieldConverter.java
- artemis/artemis-document/src/main/java/org/eclipse/jnosql/artemis/document/DocumentFieldConverters.java
- artemis/artemis-document/src/main/java/org/eclipse/jnosql/artemis/document/DocumentFieldValue.java
- artemis/artemis-graph/src/main/java/org/eclipse/jnosql/artemis/graph/AbstractGraphConverter.java
- artemis/artemis-graph/src/main/java/org/eclipse/jnosql/artemis/graph/FieldGraph.java
https://github.com/eclipse-ee4j/nosql/pull/57
> Review NoSQL API Mapping

- communication/communication-document/src/test/java/org/eclipse/jnosql/communication/document/DocumentsTest.java
- mapping/mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/DefaultColumnEntityConverterTest.java
- mapping/mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/UserScope.java
- mapping/mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/GenericFieldMapping.java
- mapping/mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DefaultDocumentEntityConverterTest.java
- mapping/mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/UserScope.java
https://github.com/eclipse/jnosql/issues/253
> Unable to Read HashMap<String, Object> from CouchDB with Artemis

- README.adoc
- mapping/pom.xml
- pom.xml
https://github.com/eclipse/jnosql/issues/250
> Remove or replace the logo

- communication/communication-column/src/main/java/org/eclipse/jnosql/communication/column/DefaultColumnEntity.java
- communication/communication-column/src/test/java/org/eclipse/jnosql/communication/column/ColumnEntityTest.java
- communication/communication-document/src/main/java/org/eclipse/jnosql/communication/document/DefaultDocument.java
- communication/communication-document/src/main/java/org/eclipse/jnosql/communication/document/DefaultDocumentEntity.java
- communication/communication-document/src/main/java/org/eclipse/jnosql/communication/document/DefaultDocumentProvider.java
- communication/communication-document/src/test/java/org/eclipse/jnosql/communication/document/DocumentEntityTest.java
- mapping/mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/AbstractGraphTemplate.java
- mapping/mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/DefaultGraphTemplate.java
- mapping/mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/GraphTemplate.java
- mapping/mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/AbstractGraphTemplateTest.java
- mapping/mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/AbstractKeyValueTemplate.java
- mapping/mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/DefaultKeyValueTemplate.java
- mapping/mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/DefaultKeyValueTemplateTest.java
https://github.com/eclipse-ee4j/nosql/pull/69
> Improves Communication and Mapping API

- mapping/mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/AbstractColumnEntityConverter.java
- mapping/mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/ColumnFieldConverters.java
- mapping/mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/entities/Citizen.java
- mapping/mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/entities/City.java
- mapping/mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/DefaultColumnEntityConverterTest.java
- mapping/mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/AbstractDocumentEntityConverter.java
- mapping/mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/DocumentFieldConverters.java
- mapping/mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DefaultDocumentEntityConverterTest.java
- mapping/mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/Citizen.java
- mapping/mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/City.java
Ref: https://github.com/eclipse/jnosql/issues/259
> Parasite property in document deserialization

- communication/communication-column/pom.xml
- communication/communication-core/pom.xml
- communication/communication-document/pom.xml
- communication/communication-key-value/pom.xml
- communication/communication-query/pom.xml
- communication/pom.xml
- mapping/mapping-column/pom.xml
- mapping/mapping-core/pom.xml
- mapping/mapping-document/pom.xml
- mapping/mapping-graph/pom.xml
- mapping/mapping-key-value/pom.xml
- mapping/mapping-reactive/mapping-reactive-column/pom.xml
- mapping/mapping-reactive/mapping-reactive-core/pom.xml
- mapping/mapping-reactive/mapping-reactive-document/pom.xml
- mapping/mapping-reactive/mapping-reactive-key-value/pom.xml
- mapping/mapping-reactive/pom.xml
- mapping/mapping-test/pom.xml
- mapping/mapping-validation/pom.xml
- mapping/pom.xml
- pom.xml
> Update to version 1.0.0-b4

- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/AbstractColumnEntityConverter.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/DefaultColumnEntityConverterInheritanceTest.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassConverter.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassMapping.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassMappingBuilder.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassMappingExtension.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassMappings.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultClassMapping.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultClassMappings.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultReflections.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/InheritanceClassMapping.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/Reflections.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassConverterTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/DefaultClassMappingsTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/ReflectionsTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/AbstractDocumentEntityConverter.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DefaultDocumentEntityConverterInheritanceTest.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/AbstractGraphConverter.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/DefaultGraphTraversalSourceConverter.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/AbstractGraphInheritanceConverterTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/DefaultGraphInheritanceConverterTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/DefaultGraphTraversalInheritanceConverterTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/EmailNotification.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/LargeProject.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/Notification.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/Project.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/SmallProject.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/SmsNotification.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/model/inheritance/SocialMediaNotification.java
https://github.com/eclipse-ee4j/nosql/issues/103
> Add support inheritance

- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/DefaultColumnEntityConverterInheritanceTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DefaultDocumentEntityConverterInheritanceTest.java
> Fixes the test on mapper

- README.adoc
This PR fixes a couple of my own minor errors.
> Fix README.adoc errors

- README.adoc
> Add the goal session at NoSQL README

- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/config/MicroProfileSettingsTest.java
#Minor
* Change a Microprofile test to pass at the eclipse jenkins instance.
* 
> Move prefix to jnosql. to avoid eclipse jenkins issue

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-core/pom.xml
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassConverter.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/EntityMetadataExtension.java
Once the annotations are not on CDI scope, this PR adds this scan using the Scan Project
> Scan elements without CDI but using Scan

- jnosql-mapping/jnosql-mapping-validation/pom.xml
- jnosql-mapping/jnosql-mapping-validation/src/main/java/org/eclipse/jnosql/mapping/validation/MappingValidator.java
- I did a little code refactoring in order to be able to improve the test coverage of the `org.eclipse.jnosql.mapping.validation.MappingValidator` class;
- Setting up the Jacoco Maven Plugin to ignore config classes;
> Code refactoring for test coverage improvement 

- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/repository/RepositoryObserverParser.java
> Update repository parser using camelcase

- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/ParamValue.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/DefaultValueTest.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/ParamValueTest.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/ValueTest.java
Added tests and refactored code to improve the project test coverage;
> Test coverage improvement

- .github/workflows/java-11.yml
Setting up a cache local for the maven repository into the GitHub Actions steps for execution performance improvement
> Setting up a cache local for the maven repository into the GitHub Actions steps

- CHANGELOG.adoc
- MIGRATION.adoc
- README.adoc
* Include migration guide file to cover the migration to version 1.0.0-b6
* Include migration session on README.
> Include the migration guide

- jnosql-communication/jnosql-communication-column/src/test/java/org/eclipse/jnosql/communication/column/ColumnDeleteQueryParamsTest.java
- Added tests for  the `ColumnDeleteQueryParams` class;
> Added tests for project test coverage improvement

- jnosql-communication/jnosql-communication-column/src/test/java/org/eclipse/jnosql/communication/column/ColumnDeleteQueryTest.java
- added tests for improvement of project code coverage
> test: added tests for improvement of project code coverage

- README.adoc
- added SonarCloud badges to the Contribution section in the README.adoc file
> Added SonarCloud badges to README.adoc file

- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassScanner.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilter.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilterTest.java
* Refactor the scan behavior to use filter classes that JNoSQL supports.
> Update ScanResult with RepositoryFilter

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- README.adoc
Closes #339 
- Adds instructions in the readme for users who want to open an issue related to JNoSQL Databases&Extensions
- Updates the feature request & bug report issue templates with a dropdown allowing the user to pick the respective project
> Add instructions for reporting issues of the JNoSQL databases & JNoSQL extensions in this repository

- README.adoc
- Fixed the link to TESTING-GUIDELINE.adoc at README.adoc
> Fixed the link to TESTING-GUIDELINE.adoc at README.adoc

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/configuration/ColumnManagerSupplier.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/configuration/DocumentManagerSupplier.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/configuration/BucketManagerSupplier.java
* Update issue message on supplier databases
> Fix supplier message

- .github/ISSUE_TEMPLATE/use_case.md
- Adding a new issue template for use case issue creation;
> Create a user case issue template

- README.adoc
- Enhance the "NoSQL Database Types" section
- Enhance the "Key-Value" section
- Enhance the "Column Family" section
- Enhance the "Graph" section
> Documentation enhancement

- jnosql-communication/jnosql-communication-column/src/test/java/org/eclipse/jnosql/communication/column/ColumnDeleteQueryParamsTest.java
My change suggestion is about `test`:
1.  It was missing an `Assertion` in this test.
Thank you.
> (test): added missing assertion

- jnosql-mapping/jnosql-mapping-graph/pom.xml
- jnosql-mapping/pom.xml
- pom.xml
- Update Neo4J version
- Update Apache Tinkerpop version to 3.6.4
- Update small eyt config
> Update Neo4J, Weld and Config

- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/FieldConverter.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/ParameterConverter.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/repository/SpecialParameters.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/FieldConverter.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/ParameterConverter.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/GremlinExecutor.java
1. In using the new feature `pattern matching for instanceof`.
3. Some cases are two/three white lines in a row, I mean it's too much, so I removed them.
Thank you.
> refact: using pattern matching for instanceof

- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/AtomicIntegerReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/AtomicLongReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/BigDecimalReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/BigIntegerReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/BooleanReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/ByteReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/CalendarReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/CharacterReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/DateReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/DoubleReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/EnumReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/FloatReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/IntegerReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/ListTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/LocalDateReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/LocalDateTimeReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/LocalTimeReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/LongReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/MapTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/NavigableSetTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/NumberReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/OffsetDateTimeReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/OffsetTimeReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/OptionalTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/QueueTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/SetTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/ShortReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/StreamTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/ZonedDateTimeReader.java
1. In using the new feature `pattern matching for instanceof`.
3. Some cases are two/three white lines in a row, I mean it's too much, so I removed them.
Thank you.
> feat: pattern matcher for instanceof

- jnosql-mapping/jnosql-mapping-core/pom.xml
- pom.xml
- Update Jupiter version
- Update CDI Weld version
- Update Config version
> Update version of Jakarta Data and other libraries

- jnosql-mapping/jnosql-mapping-document/src/main/resources/META-INF/services/jakarta.nosql.mapping.document.DocumentQueryPagination$DocumentQueryPaginationProvider
- Removed unused provider configuration file;
> Removed unused provider configuration file

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/AbstractColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/PersonStatisticRepository.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/PersonStatisticRepositoryProducer.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/query/RepositoryType.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/query/RepositoryTypeTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/AbstractDocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/PersonStatisticRepository.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/PersonStatisticRepositoryProducer.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractGraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/entities/PersonStatisticRepository.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/entities/PersonStatisticRepositoryProducer.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/AbstractKeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/test/entities/PersonStatisticRepository.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/test/entities/PersonStatisticRepositoryProducer.java
- Add support for custom repository
Solve this: https://github.com/eclipse/jnosql/issues/414
> Add support for Custom Repository

- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/spi/EntityMetadataExtension.java
Separating responsibilities to improve readability and maintainability
> improve readability and maintainability

- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/BaseColumnRepository.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/DynamicQuery.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/DynamicQueryTest.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/repository/SpecialParameters.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/repository/SpecialParametersTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/DynamicQuery.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DynamicQueryTest.java
- This PR creates a unique class to handle with special parameters in repository feature
> Create Special Paramter converter

- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/AbstractColumnTemplate.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/AbstractColumnRepository.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/DefaultColumnTemplateTest.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/AbstractDocumentTemplate.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/AbstractDocumentRepository.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DefaultDocumentTemplateTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/AbstractGraphTemplate.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/GraphTemplate.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractGraphRepository.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/AbstractGraphTemplateTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/AbstractTraversalTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/EdgeEntityTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphCrudRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/AbstractKeyValueTemplate.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/AbstractKeyValueRepository.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/DefaultKeyValueRepository.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProducer.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/RepositoryKeyValueBean.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/DefaultKeyValueTemplateTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxyTest.java
- pom.xml
- Downgrade into Jakarta NoSQL b7
- Update the API using the normal API.
> Downgrade Jakarta NoSQL API

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-graph/pom.xml
- jnosql-mapping/jnosql-mapping-reflection/pom.xml
- jnosql-mapping/pom.xml
- pom.xml
- Update Apache Tinkerpop to version 3.7.0
- Update classpath to version 4.8.162
- Update Mockito version to 5.5.0
> Update dependencies at Eclipse JNoSQL

- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/AbstractColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/query/RepositoryType.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/query/RepositoryTypeTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/AbstractDocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractGraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/AbstractKeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxy.java
- Update RepositoryType validation
- Fixes repository action type avoiding overflow exception
> Fix custom repository

- CHANGELOG.adoc
- antlr4/org/eclipse/jnosql/query/grammar/Query.g4
- antlr4/org/eclipse/jnosql/query/grammar/method/Method.g4
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/SelectQueryConverterTest.java
- jnosql-communication/jnosql-communication-query/src/test/resources/delete_jnosql.nosql
- jnosql-communication/jnosql-communication-query/src/test/resources/insert_jnosql.nosql
- jnosql-communication/jnosql-communication-query/src/test/resources/select_jnosql.nosql
- Fixes https://github.com/eclipse/jnosql/issues/441
> query specification doesnt allow for dashes in tablenames

- CHANGELOG.adoc
- README.adoc
- jnosql-communication/jnosql-communication-column/pom.xml
- jnosql-communication/jnosql-communication-core/pom.xml
- jnosql-communication/jnosql-communication-document/pom.xml
- jnosql-communication/jnosql-communication-key-value/pom.xml
- jnosql-communication/jnosql-communication-query/pom.xml
- jnosql-communication/pom.xml
- jnosql-mapping/jnosql-mapping-api-core/pom.xml
- jnosql-mapping/jnosql-mapping-column/pom.xml
- jnosql-mapping/jnosql-mapping-core/pom.xml
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/config/MicroProfileSettings.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/config/MicroProfileSettingsTest.java
- jnosql-mapping/jnosql-mapping-document/pom.xml
- jnosql-mapping/jnosql-mapping-graph/pom.xml
- jnosql-mapping/jnosql-mapping-key-value/pom.xml
- jnosql-mapping/jnosql-mapping-reflection/pom.xml
- jnosql-mapping/pom.xml
- pom.xml
- Update the documentation at 1.0.2
> Update release 1.0.2 version

- jnosql-communication/jnosql-communication-column/src/main/java/org/eclipse/jnosql/communication/column/DefaultColumnDeleteQuery.java
- jnosql-communication/jnosql-communication-column/src/main/java/org/eclipse/jnosql/communication/column/DefaultColumnQuery.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/DefaultValue.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/ParamsTest.java
- jnosql-communication/jnosql-communication-document/src/main/java/org/eclipse/jnosql/communication/document/DefaultDocumentDeleteQuery.java
- jnosql-communication/jnosql-communication-document/src/main/java/org/eclipse/jnosql/communication/document/DefaultDocumentQuery.java
- jnosql-communication/jnosql-communication-document/src/main/java/org/eclipse/jnosql/communication/document/DocumentEntity.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/BooleanQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/ConditionQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/DefaultArrayQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/DefaultFunction.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/DefaultQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/DefaultSelectQuery.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/DeleteQuery.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/FunctionQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/GetQuery.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/InsertQuery.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/NumberQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/StringQueryValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/UpdateQuery.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/Where.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/method/MethodArrayValue.java
- jnosql-communication/jnosql-communication-query/src/main/java/org/eclipse/jnosql/communication/query/method/MethodParamQueryValue.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/InsertQueryConverterTest.java
- jnosql-communication/jnosql-communication-query/src/test/java/org/eclipse/jnosql/communication/query/SelectQueryConverterTest.java
- jnosql-mapping/jnosql-mapping-api-core/src/main/java/org/eclipse/jnosql/mapping/metadata/InheritanceMetadata.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/spi/AbstractBeanTest.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/DefaultPropertyTest.java
> Refactoring the current code

- CHANGELOG.adoc
- README.adoc
- jnosql-communication/jnosql-communication-column/pom.xml
- jnosql-communication/jnosql-communication-core/pom.xml
- jnosql-communication/jnosql-communication-document/pom.xml
- jnosql-communication/jnosql-communication-key-value/pom.xml
- jnosql-communication/jnosql-communication-query/pom.xml
- jnosql-communication/pom.xml
- jnosql-mapping/jnosql-mapping-api-core/pom.xml
- jnosql-mapping/jnosql-mapping-column/pom.xml
- jnosql-mapping/jnosql-mapping-core/pom.xml
- jnosql-mapping/jnosql-mapping-document/pom.xml
- jnosql-mapping/jnosql-mapping-graph/pom.xml
- jnosql-mapping/jnosql-mapping-key-value/pom.xml
- jnosql-mapping/jnosql-mapping-reflection/pom.xml
- jnosql-mapping/pom.xml
- pom.xml
> Upgrade JNoSQL to version 1.0.3

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/ColumnEntityConverter.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/ParameterConverter.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/ColumnEntityConverterConstructorTest.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/constructor/SuperHero.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/DocumentEntityConverter.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/ParameterConverter.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DocumentEntityConverterConstructorTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/constructor/Hero.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/constructor/SuperHero.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/ParameterMetaDataBuilderTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/test/entities/constructor/SuperHero.java
- Fix serialization when the entity has constructor with simple generic types
> Fix serialization when parameter is generic

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/FieldConverter.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/ColumnEntityConverterTest.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/MainStepType.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/StepTransitionReason.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/Transition.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/WorkflowStep.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/entities/WorkflowStepBuilder.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/FieldConverter.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/DocumentEntityConverterTest.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/MainStepType.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/StepTransitionReason.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/Transition.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/WorkflowStep.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/entities/WorkflowStepBuilder.java
- https://github.com/eclipse/jnosql/issues/460
> [BUG] Embeddable list of nested object cannot be saved

- pom.xml
- update commons io
- upgrade mockito
-
> Upgrade mockito version

- CHANGELOG.adoc
- README.adoc
- jnosql-communication/jnosql-communication-column/pom.xml
- jnosql-communication/jnosql-communication-core/pom.xml
- jnosql-communication/jnosql-communication-document/pom.xml
- jnosql-communication/jnosql-communication-key-value/pom.xml
- jnosql-communication/jnosql-communication-query/pom.xml
- jnosql-communication/pom.xml
- jnosql-mapping/jnosql-mapping-api-core/pom.xml
- jnosql-mapping/jnosql-mapping-column/pom.xml
- jnosql-mapping/jnosql-mapping-core/pom.xml
- jnosql-mapping/jnosql-mapping-document/pom.xml
- jnosql-mapping/jnosql-mapping-graph/pom.xml
- jnosql-mapping/jnosql-mapping-key-value/pom.xml
- jnosql-mapping/jnosql-mapping-reflection/pom.xml
- jnosql-mapping/pom.xml
- pom.xml
> Release version 1.0.4

- jnosql-communication/jnosql-communication-document/src/main/java/org/eclipse/jnosql/communication/document/UpdateQueryParser.java
> Fixed class name typo

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/AbstractColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/BaseColumnRepository.java
- jnosql-mapping/jnosql-mapping-column/src/main/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-column/src/test/java/org/eclipse/jnosql/mapping/column/query/ColumnRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/query/AbstractRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/query/AnnotationOperation.java
- jnosql-mapping/jnosql-mapping-core/src/main/java/org/eclipse/jnosql/mapping/core/query/RepositoryType.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/core/query/AnnotationOperationTest.java
- jnosql-mapping/jnosql-mapping-core/src/test/java/org/eclipse/jnosql/mapping/core/query/RepositoryTypeTest.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/AbstractDocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/BaseDocumentRepository.java
- jnosql-mapping/jnosql-mapping-document/src/main/java/org/eclipse/jnosql/mapping/document/query/DocumentRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-document/src/test/java/org/eclipse/jnosql/mapping/document/query/DocumentCrudRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/AbstractGraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/main/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-graph/src/test/java/org/eclipse/jnosql/mapping/graph/query/GraphRepositoryProxyTest.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/AbstractKeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/main/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-key-value/src/test/java/org/eclipse/jnosql/mapping/keyvalue/query/KeyValueRepositoryProxyTest.java
-  Include support to annotation operation (Insert, Update, Delete and Save) from Jakarta Data
> Include Support to Annotation operation

- pom.xml
- Add DataFaker library for test support
> Add datafaker library for test support

- CHANGELOG.adoc
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/MapTypeReferenceReader.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/reader/MapTypeReferenceReaderTest.java
- Include support to interaction to Map
https://github.com/eclipse/jnosql-databases/pull/263/#issuecomment-1918719396
> Fix map reader

- CHANGELOG.adoc
- README.adoc
- jnosql-communication/jnosql-communication-column/pom.xml
- jnosql-communication/jnosql-communication-core/pom.xml
- jnosql-communication/jnosql-communication-document/pom.xml
- jnosql-communication/jnosql-communication-key-value/pom.xml
- jnosql-communication/jnosql-communication-query/pom.xml
- jnosql-communication/pom.xml
- jnosql-mapping/jnosql-mapping-api-core/pom.xml
- jnosql-mapping/jnosql-mapping-column/pom.xml
- jnosql-mapping/jnosql-mapping-core/pom.xml
- jnosql-mapping/jnosql-mapping-document/pom.xml
- jnosql-mapping/jnosql-mapping-graph/pom.xml
- jnosql-mapping/jnosql-mapping-key-value/pom.xml
- jnosql-mapping/jnosql-mapping-reflection/pom.xml
- jnosql-mapping/pom.xml
- pom.xml
-  Upgrade documentation to version 1.1.0
- Upgrade pom to version 1.1.0
- Upgrade changelog to version 1.1.0
> Upgrade version to 1.1.0

- jnosql-mapping/pom.xml
- pom.xml
Update those libraries to the newest version:
- weld.jupiter
- weld.se.core
- junit
- mockito
- datafaker
- assertj
> Update Eclipse JNoSQL dependencies

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-api-core/src/main/java/org/eclipse/jnosql/mapping/metadata/MappingType.java
- jnosql-mapping/jnosql-mapping-api-core/src/test/java/org/eclipse/jnosql/mapping/metadata/MappingTypeTest.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/DefaultAttributeFieldValue.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/EntityConverter.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/FieldConverter.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/ParameterConverter.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/EntityConverterConstructorTest.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/EntityConverterTest.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/entities/Wine.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/entities/WineFactory.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/entities/constructor/Beer.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/entities/constructor/BeerFactory.java
> Include support to Embbeded group

- .github/workflows/tck-runner.yml
- pom.xml
- tck-runner/logging.properties
- tck-runner/pom.xml
Still some bugs to work out, but this should give you a good start towards certifying against the Jakarta Data TCK.
> Add Jakarta Data TCK runner

- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScanner.java
> Avoid MappingException for other Jakarta Data providers

- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultEntitiesMetadata.java
> fix: fully thread safe DefaultEntitiesMetadata as it is @ApplicationScoped

- jnosql-communication/jnosql-communication-semistructured/src/main/java/org/eclipse/jnosql/communication/semistructured/QueryParser.java
- jnosql-communication/jnosql-communication-semistructured/src/test/java/org/eclipse/jnosql/communication/semistructured/DefaultElementQueryParserTest.java
- Fix query parser to support statement commands with case-insensitive;
> Fix query parser to support statement commands with case-insensitive;

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepository.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/query/RepositoryProxyTest.java
-  Include annotation and fixing the mapping
> Fix Order annotation

- jnosql-mapping/jnosql-mapping-reflection/pom.xml
There where important updates for the WildFly VFS scanning
> update classgraph library to 4.8.174

- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScanner.java
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilter.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/ClassGraphClassScannerTest.java
- jnosql-mapping/jnosql-mapping-reflection/src/test/java/org/eclipse/jnosql/mapping/reflection/RepositoryFilterTest.java
> Add jnosql provider name

- README.adoc
Adjusted some incorrectly words in README file.
> docs: fixed typo on readme file

- CHANGELOG.adoc
- jnosql-communication/jnosql-communication-core/src/main/java/module-info.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/InstantReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/OffsetDateTimeReader.java
- jnosql-communication/jnosql-communication-core/src/main/java/org/eclipse/jnosql/communication/reader/YearMonthReader.java
- jnosql-communication/jnosql-communication-core/src/main/resources/META-INF/services/org.eclipse.jnosql.communication.ValueReader
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/reader/InstantReaderTest.java
- jnosql-communication/jnosql-communication-core/src/test/java/org/eclipse/jnosql/communication/reader/OffsetDateTimeReaderTest.java
Fixes: https://github.com/eclipse-jnosql/jnosql/issues/585
> Include Reader for instant

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultEntitiesMetadata.java
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/Reflections.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/AbstractSemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/BaseSemiStructuredRepository.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandler.java
- jnosql-mapping/jnosql-mapping-semistructured/src/test/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandlerTest.java
- Fixed the AbstractSemiStructuredTemplate class to apply the inheritance strategy properly on find and delete methods
- Adjustments at CustomRepositoryHandler to handle inheritance correctly
> Fixes and adjustments at the AbstractSemiStructuredTemplate and CustomRepositoryHandler classes to handle inheritance correctly

- CHANGELOG.adoc
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/DefaultEntitiesMetadata.java
- jnosql-mapping/jnosql-mapping-reflection/src/main/java/org/eclipse/jnosql/mapping/reflection/Reflections.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/AbstractSemiStructuredTemplate.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/CustomRepositoryHandler.java
It's a backport from https://github.com/eclipse-jnosql/jnosql/pull/607
- Fixed the AbstractSemiStructuredTemplate class to apply the inheritance strategy properly on find and delete methods
- Adjustments at CustomRepositoryHandler to handle inheritance correctly
> Fixes and adjustments at the AbstractSemiStructuredTemplate and CustomRepositoryHandler classes to handle inheritance correctly 

- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/AbstractSemiStructuredRepositoryProxy.java
- jnosql-mapping/jnosql-mapping-semistructured/src/main/java/org/eclipse/jnosql/mapping/semistructured/query/SemiStructuredParameterBasedQuery.java
> feat: Allow overriding query creation in SemiStructured proxies
